service: serverless-expressjs

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.handler # refers to handler.js and module handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-offline
