service: teabag

provider:
  name: aws
  runtime: nodejs8.10

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true
plugins:
  - serverless-offline
