service: teabag

custom:
  secrets: ${file(./secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true

  verify-token:
    handler: auth.VerifyToken.auth

  login:
    handler: auth/AuthHandler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  register:
    handler: auth/AuthHandler.register
    events:
      - http:
          path: register
          method: post
          cors: true

plugins:
  - serverless-offline
