service: serverless-expressjs

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/get
          method: get
  greet:
    handler: handler.greet
    events:
      - http:
          path: greet/get
          method: get
plugins:
  - serverless-offline
